### PR TITLE
Fix syntax highlighting in README.md

### PR DESCRIPTION
**Pull request by MaxDesiatov**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
I really hope that the bot is fixed soon. Not only it spams here, but also spams with emails if you have email notifications enabled. I mentioned previously that I would be happy to help with fixing the bot, but it doesn't look like the bot is open-source or if there's any other way to help.

This currently gives an impression that the infrastructure is broken and is not maintained, and maye also be off-putting for new contributors.

**Comment by yim-lee** [comment]
@swift-server-bot please test this

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
Thanks for the PR and comment @ MaxDesiatov. cc @apple/swift-server-admins

**Review by yim-lee — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@yim-lee Thanks for merging and thanks for the great library!

**Pull request merged**
