### PR TITLE
Adopt swift-atomics

### PR DESCRIPTION
**Pull request by yim-lee**
Remove `CServiceDiscoveryHelpers` and `ServiceDiscoveryHelpers` modules.

Depends on https://github.com/apple/swift-service-discovery/pull/36. Relevant commit: https://github.com/apple/swift-service-discovery/commit/6ebd9d21d4ce2b1b74d0ecff456738bab21f35cd

### CODE REVIEW

**Comment by yim-lee** [comment]
5.1 and 5.2 failures expected since swift-atomics requires >= 5.3

**Review by ktoso — APPROVED** [review]
Sweet! :)

**Comment by tomerd** [comment]
do we want to move the library require min of 5.3? rio now requires 5.2 iirc so I can see an argument both ways

**Comment by yim-lee** [comment]
@tomerd Updated in https://github.com/apple/swift-service-discovery/pull/37/commits/ecedb60f1e580dcb0f70b914e9a8ad6b12721beb

**Review by tomerd — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Pull request merged**
